# MariaDB Persistent Volume Claim

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mariadb-pvc
  namespace: exercise01
  # We use labels here to classify the service itself as well
  labels:
    app: wordpress
    type: database
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
