############################ # ############################
## Bitnami K8S training
## session02/exercise02
#
## Author: Antonio Gamez-Diaz
## Contact: antoniogamez@us.es
#
# File: dbDump secret creation
# Purpose: creates b64-encoded secrets for dbDump
############################ # ############################
---
{{- if .Values.dbDump.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ template "fullname" . }}-dbdump-secret
  labels:
    app: {{ template "fullname" . }}
    chart: {{ .Chart.Name }}-{{ .Chart.Version }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
type: Opaque
data:
  dbuser: {{ .Values.dbDump.dbuser | b64enc }} # root
  dbpass: {{ .Values.dbDump.dbpass | b64enc }} # root_password
{{- end }}