############################ # ############################
## Bitnami K8S training
## session03/exercise01
#
## Author: Antonio Gamez-Diaz
## Contact: antoniogamez@us.es
#
# File: wordpress configmap creation
# Purpose: creates key/value pairs to be used in wordpress
############################ # ############################
---
{{- if .Values.dbDump.enabled }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ template "fullname" . }}-dbdump-cm
  labels:
    app: {{ template "fullname" . }}
    chart: {{ .Chart.Name }}-{{ .Chart.Version }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
data:
  {{- if .Values.mariadb.enabled }}
  dbhost: {{ template "mariadb.fullname" . }}
  {{- end }}
  {{- if .Values.mysql.enabled }}
  dbhost: {{ template "mysql.fullname" . }}
  {{- end }}
  all_databases: {{ .Values.dbDump.all_databases | quote }}
{{- end }}
