# ############################ # ############################
# ## Bitnami K8S training
# ## session03/exercise01
# #
# ## Author: Antonio Gamez-Diaz
# ## Contact: antoniogamez@us.es
# #
# # File: dbDump pv claim creation
# # Purpose: allocates some persistence
# ############################ # ############################
---
{{- if .Values.dbDump.enabled }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ template "fullname" . }}-dbdump-pvc
  labels:
    app: {{ template "fullname" . }}
    chart: {{ .Chart.Name }}-{{ .Chart.Version }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  accessModes:
    - {{ .Values.dbDump.persistence.accessMode | quote }}
  resources:
    requests:
      storage: {{ .Values.dbDump.persistence.size | quote }}
{{- if .Values.dbDump.persistence.storageClass }}
{{- if (eq "-" .Values.dbDump.persistence.storageClass) }}
  storageClassName: ""
{{- else }}
  storageClassName: {{ .Values.dbDump.persistence.storageClass }}
{{- end }}
{{- end }}

{{- end }}



