############################ # ############################
## Bitnami K8S training
## session03/exercise01
#
## Author: Antonio Gamez-Diaz
## Contact: antoniogamez@us.es
#
# File: NetworkPolicy to deny all connections
# Purpose: denies all connections between pods
############################ # ############################
---
{{- if .Values.netpol.enabled }}
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: {{ template "fullname" . }}-netpol-deny-all
  labels:
    app: {{ template "fullname" . }}
    chart: {{ .Chart.Name }}-{{ .Chart.Version }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  podSelector: {}
  policyTypes:
  - Ingress
{{- end }}