# ############################ # ############################
# ## Bitnami K8S training
# ## session03/exercise01
# #
# ## Author: Antonio Gamez-Diaz
# ## Contact: antoniogamez@us.es
# #
# # File: wordpress ingress
# # Purpose: redirects host/ to wordpress service
# ############################ # ############################
---
{{- if .Values.ingress.enabled }}
{{- range .Values.ingress.hosts }}
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: {{ template "fullname" $ }}-ingress
  labels:
    app: {{ template "fullname" $ }}
    chart: {{ $.Chart.Name }}-{{ $.Chart.Version }}
    release: {{ $.Release.Name }}
    heritage: {{ $.Release.Service }}
  annotations:
    {{- if .tls }}
    ingress.kubernetes.io/secure-backends: "true"
    {{- end }}
    {{- if $.Values.certManager.enabled}}
    kubernetes.io/tls-acme: "true"
    {{- end }}
    {{- range $key, $value := .annotations }}
    {{ $key }}: {{ $value | quote }}
    {{- end }}
spec:
  rules:
  - host: {{ .name }}
    http:
      paths:
        - path: {{ default "/" .path }}
          backend:
            serviceName: {{ template "fullname" $ }}
            servicePort: 80
{{- if .tls }}
  tls:
  - hosts:
    - {{ .name }}
    secretName: {{ template "fullname" $ }}-certificate
{{- end }}
---
{{- end }}
{{- end }}