############################ # ############################
## Bitnami K8S training
## session03/exercise01
#
## Author: Antonio Gamez-Diaz
## Contact: antoniogamez@us.es
#
# File: wordpress secret creation
# Purpose: creates b64-encoded secrets for Wordpress
############################ # ############################
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ template "fullname" . }}-secret
  labels:
    app: {{ template "fullname" . }}
    chart: {{ .Chart.Name }}-{{ .Chart.Version }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
type: Opaque
data:
  WORDPRESS_DATABASE_NAME: {{ .Values.wordpressConfig.databaseName | b64enc }}  # database_wp
  WORDPRESS_DATABASE_USER: {{ .Values.wordpressConfig.databaseUser | b64enc }}  # dbuser_wp
  WORDPRESS_DATABASE_PASSWORD: {{ .Values.wordpressConfig.databasePassword | b64enc }}  # dbuser_password
  
  WORDPRESS_USERNAME: {{ .Values.wordpressConfig.wpUser | b64enc }}  # antonio
  WORDPRESS_PASSWORD: {{ .Values.wordpressConfig.wpPassword | b64enc }}  # antonio_wp

  MARIADB_ROOT_USER: {{ .Values.wordpressConfig.dbRootUser | b64enc }}  # root
  MARIADB_ROOT_PASSWORD: {{ .Values.wordpressConfig.dbRootPassword | b64enc }}  # root_password