apiVersion: v1
kind: Service
metadata:
  name: wordpress
  namespace: exercise-02
spec:
  type: LoadBalancer
  ports:
  - name: wordpress
    port: 8001
    targetPort: 80
  selector:
    app: wordpress
  sessionAffinity: ClientIP

