kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: {{ template "fullname" . }}-crb
subjects:
- kind: ServiceAccount
  name: {{ template "fullname" . }}-sa
  namespace: logging
roleRef:
  kind: ClusterRole
  name: {{ template "fullname" . }}-cr
  apiGroup: rbac.authorization.k8s.io