{{- if .Values.ingress.enabled }}

apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: {{ template "fullname" . }}
  
   labels:
    app: {{ template "fullname" . }}
    chart: "{{ $.Chart.Name }}-{{ $.Chart.Version }}"
  annotations:
    ingress.kubernetes.io/secure-backends: "true"
    {{- if .certManager }}
    kubernetes.io/tls-acme: "true"
    {{- end }}
    {{- range $key, $value := .annotations }}
    {{ $key }}: {{ $value | quote }}
    {{- end }}
spec:
  rules:
  - host: {{ .name }}
    http:
      paths:
        - path: /
          backend:
            serviceName: {{ template "fullname" $ }}
            servicePort: 80
{{- if .tls }}
  tls:
  - hosts:
    - {{ .name }}
    secretName: {{ .tlsSecret }}
{{- end }}
---
{{- end }}
