############################ # ############################
## Bitnami K8S training
## session03/exercise01
#
## Author: Antonio Gamez-Diaz
## Contact: antoniogamez@us.es
#
# File: ClusterRole for retrieving deployments 
# Purpose: defines a read-only role for deployments 
############################ # ############################
---
kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: deployment-ro-clusterrole
rules:
- apiGroups: ["extensions/v1beta1"]
  resources: ["deployment"]
  verbs: ["get", "watch", "list"]