apiVersion: v1
kind: Pod
metadata:
  name: two-containers
spec:

  restartPolicy: Never

  volumes:
  - name: volume-1
    emptyDir: {}
  - name: volume-2
    emptyDir: {}    

  containers:

  - name: nginx-container
    image: nginx
    volumeMounts:
    - name: volume-1
      mountPath: /usr/share/nginx/html
    - name: volume-2
      mountPath: /volume-2      

  - name: debian-container
    image: debian
    volumeMounts:
    - name: volume-1
      mountPath: /volume-1
    - name: volume-2
      mountPath: /volume-2
    command: ["/bin/sh", "-c"]
    args:
      - while true; do
          cp /volume-1/* /volume-2;          
          sleep 600;
        done    