apiVersion: v1
kind: Secret
metadata:
  name: {{ template "fullname" . }}-wp-secret
  labels:
    app: {{ template "fullname" . }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    release: "{{ .Release.Name }}"
    heritage: "{{ .Release.Service }}"
type: Opaque
data:
  wp-db-name: {{ .Values.wordpressDatabaseName | b64enc }}
  wp-db-user: {{ .Values.wordpressDatabaseUser | b64enc }}
  wp-db-pass: {{ .Values.wordpressDatabasePassword | b64enc }}

  wp-user: {{ .Values.wordpressUsername | b64enc }}
  wp-pass: {{ .Values.wordpressPassword | b64enc }}

  wp-table-prefix: {{ .Values.wordpressTablePrefix | b64enc }}
  mariadb-root-user: {{ .Values.mariadbRootUser| b64enc }}
  mariadb-root-password: {{ .Values.mariadbRootPassword | b64enc }}
