# WordPress Persistent Volume Claim

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: wordpress-pvc
  namespace: exercise03
  # We use labels here to classify the service itself as well
  labels:
    app: wordpress
    type: frontend
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
