apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: mariadb-slave-deployment
  namespace: exercise02
spec:
  replicas: 2
  selector:
    matchLabels:
      app: wordpress
      role: slave
      type: backend
  template:
    metadata:
      labels:
        app: wordpress
        role: slave
        type: backend
    spec:
      containers:
        - image: bitnami/mariadb:latest
          name: mariadb
          env:
            - name: MARIADB_DATABASE
              valueFrom:
                configMapKeyRef:
                  name: exercise02-config
                  key: MARIADB_DATABASE
            - name: MARIADB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mariadb-pass-user
                  key: password
            - name: MARIADB_REPLICATION_MODE
              valueFrom:
                configMapKeyRef:
                  name: exercise02-config
                  key: MARIADB_REPLICATION_MODE_SLAVE
            - name: MARIADB_MASTER_HOST
              value: mariadb-service-master
            - name: MARIADB_REPLICATION_USER
              valueFrom:
                configMapKeyRef:
                  name: exercise02-config
                  key: MARIADB_REPLICATION_USER
            - name: MARIADB_REPLICATION_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mariadb-pass-replication-user
                  key: password
            - name: MARIADB_MASTER_ROOT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mariadb
                  key: password
            - name: MARIADB_USER
              valueFrom:
                configMapKeyRef:
                  name: exercise02-config
                  key: MARIADB_MASTER_USER
            - name: MARIADB_MASTER_PORT
              valueFrom:
                configMapKeyRef:
                  name: exercise02-config
                  key: MARIADB_PORT
            - name: MARIADB_MASTER_PORT_NUMBER
              valueFrom:
                configMapKeyRef:
                  name: exercise02-config
                  key: MARIADB_PORT
            - name: MARIADB_MASTER_ROOT_USER
              valueFrom:
                configMapKeyRef:
                  name: exercise02-config
                  key: MARIADB_MASTER_USER
          resources:
            requests:
              memory: "128Mi"
              cpu: "250m"
            limits:
              memory: "256Mi"
              cpu: "500m"
          ports:
            - containerPort: 3306
              name: mariadb-port
          readinessProbe:
            exec:
              command:
                - sh
                - -c
                - "mysqladmin ping -u root -p${MARIADB_ROOT_PASSWORD}"
            initialDelaySeconds: 100
            periodSeconds: 10
            successThreshold: 1
            failureThreshold: 5
            timeoutSeconds: 5
          livenessProbe:
            exec:
              command:
                - sh
                - -c
                - "mysqladmin ping -u root -p${MARIADB_ROOT_PASSWORD}"
            initialDelaySeconds: 100
            periodSeconds: 10
            successThreshold: 1
            failureThreshold: 5
            timeoutSeconds: 5
      restartPolicy: Always
  revisionHistoryLimit: 5
  minReadySeconds: 20
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 40%
      maxSurge: 2
