dependencies:
- name: mariadb
  version: 5.x.x
  repository: https://kubernetes-charts.storage.googleapis.com/
  condition: mariadb.enabled
  tags:
    - mariadb-database
- name: mysql
  version: 0.10.x
  repository: https://kubernetes-charts.storage.googleapis.com/
  condition: mysql.enabled
  tags:
    - wordpress-database
